export default [
  {
    id: 41,
    homeTeam: 'São Paulo',
    homeTeamGoals: '2',
    away_team: 'Internacional',
    away_teamGoals: '0',
    in_progress: true,
  },
  {
    id: 42,
    homeTeam: 'Ferroviária',
    homeTeamGoals: '1',
    away_team: 'Avaí/Kindermann',
    away_teamGoals: '0',
    in_progress: true,
  },
  {
    id: 43,
    homeTeam: 'Napoli-SC',
    homeTeamGoals: '0',
    away_team: 'Minas Brasília',
    away_teamGoals: '0',
    in_progress: true,
  },
  {
    id: 46,
    homeTeam: 'Corinthians',
    homeTeamGoals: '1',
    away_team: 'Palmeiras',
    away_teamGoals: '1',
    in_progress: true,
  },
  {
    id: 47,
    homeTeam: 'Grêmio',
    homeTeamGoals: '1',
    away_team: 'Santos',
    away_teamGoals: '2',
    in_progress: false,
  },
  {
    id: 48,
    homeTeam: 'Real Brasília',
    homeTeamGoals: '1',
    away_team: 'Bahia',
    away_teamGoals: '1',
    in_progress: false,
  }
];
