export default [
  {
    id: 41,
    home_team: 'São Paulo',
    home_team_goals: '2',
    away_team: 'Internacional',
    away_team_goals: '0',
    in_progress: true,
  },
  {
    id: 42,
    home_team: 'Ferroviária',
    home_team_goals: '1',
    away_team: 'Avaí/Kindermann',
    away_team_goals: '0',
    in_progress: true,
  },
  {
    id: 43,
    home_team: 'Napoli-SC',
    home_team_goals: '0',
    away_team: 'Minas Brasília',
    away_team_goals: '0',
    in_progress: true,
  },
  {
    id: 46,
    home_team: 'Corinthians',
    home_team_goals: '1',
    away_team: 'Palmeiras',
    away_team_goals: '1',
    in_progress: true,
  },
  {
    id: 47,
    home_team: 'Grêmio',
    home_team_goals: '1',
    away_team: 'Santos',
    away_team_goals: '2',
    in_progress: false,
  },
  {
    id: 48,
    home_team: 'Real Brasília',
    home_team_goals: '1',
    away_team: 'Bahia',
    away_team_goals: '1',
    in_progress: false,
  }
];
